### ISSUE TITLE
Generate migrations for differences between two spaces

### ISSUE THREAD

**Issue by tomardern** [contentful/contentful-cli#1007]
## Expected Behavior
To easily allow for migration files to be created, the tool could generate the difference between  environments.

## Actual Behavior

New feature request

## Possible Solution

Example of possible command structure: 
`contentful space generate migration --environment-id test-env --environment-base-id master`

This would then create the migration files which could be ran against the "base environment" to bring it in-line with that of the "test-env" (in the example above)

## Steps to Reproduce

N/a - Feature request

## Context

We're trying to simplify our migration scripts to help manage our content models in code.

## Environment

N/a

**Comment by funkeeflow** [comment]
any update in this? would be awesome to have this, since this is a common use case in my option. +1

**Comment by qlemaire22** [comment]
Hi! Is there any update on this? Thanks!

**Comment by callum-gander** [comment]
This would be a really useful feature to speed up the manual parts of migrations and reduce errors from the CLI tool. For example, sometimes it'll incorrectly write createContentType instead of editContentType when that content type already exists because it's applying the migration from scratch rather than in comparison to an existing environment that already has most of those content types. It just wastes quite a bit of developer time sorting out these small mistakes, it'd be a really great feature for you to build

**Comment by marcolink** [comment]
Hi @callum-gander @qlemaire22 @funkeeflow @tomardern 👋 
Sorry for only coming back to this issue now, but I might have some good news for you:

Over the last year, we have developed a new app (the [**Merge App**](https://www.contentful.com/marketplace/app/merge/)) that let's you diff and merge your content models across environments. The app also allows for directly merging the differences to the target environment. 

Additionally, the **Merge App CLI** allows for diffing and exporting migration scripts programatically. [Find out more in the docs](https://www.contentful.com/developers/docs/tutorials/cli/merge-app-cli/)! 

I will close the issue for now - but please let us know if you have further questions.
