### ISSUE TITLE
Query entries to exclude certain content_types

### ISSUE THREAD

**Issue by kevcodez** [contentful/contentful-cli#196]
Using `--query-entries 'content_type=foobar'` works as expected.

However, `--query-entries 'content_type[nin]=foobar'` results in 

>  The path "'content_type" is not recognized

Any help would be appreciated

**Comment by ruderngespra** [comment]
Hey, thanks for the comment!

You can currently use the `[nin]` parameter only on fields and not directly on content types which is why your second query does not work.

The `[nin]` parameter should work however with a command like the following:

    contentful space export --space-id <your_space_id>  --query-entries 'content_type=<your_content_type_id>&fields.<your_field_name>[nin]=foobar'

For further reference see _Filtering Results_ in [the User Management API reference](https://www.contentful.com/developers/docs/references/user-management-api/) as well as the [exclusion entry](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/exclusion) in the Content Delivery API reference.
