### ISSUE TITLE
1.4.4 yargs update causes "unknown argument" error

### ISSUE THREAD

**Issue by DeathstarNovember** [contentful/contentful-cli#432]
## Expected Behavior

contentful-cli accepts provided arguments.

## Actual Behavior

Running `contentful space ...`, produces an 'unknown argument' error.

## Steps to Reproduce
Scripted example here:
https://codesandbox.io/s/contentful-migration-issue-r5e4j?file=/package.json

## Context

Initiating a new project with a migration using contentful-cli.

Reverting to 1.4.3 resolved yargs issue.

## Environment

-   **Language Version**: 10.15.3
-   **Package Manager Version**: 6.4.1
-   **Browser Version**: 19.4.0
-   **Operating System**: Darwin Kernel Version 19.4.0
-   **Package Version**: 1.4.4

**Comment by lcanizzo** [comment]
Confirming this issue running: `contentful space migration` command specifically

- Using args results in: 'Unknown argument: whatever-migration-file.js'
- Using the `--config` flag with no file path results in: 'Invalid JSON config file: true'
- Using a JSON config file results in: 'Please provide the file containing the migration script.' _which is weird because at that point I expected another `Unkown argument` error_

Using contentful-cli@1.4.3 runs migration scripts as expected documented.
